---
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: dashdb
    driver:
      name: vagrant
      network:
        private_network:
          type: dhcp
    run_list:
      - recipe[core::install_mysql]
    attributes:
    

  - name: dashapp
    driver:
      name: vagrant
      network:
        private_network:
          type: dhcp
        forwarded_port:
          guest: 8080
          host: 8080
    run_list:
      - recipe[core::default]
    # verifier:
    #   inspec_tests:
    #     - test/smoke/default
    attributes:
      java:
        jdk_version: '8'
        install_flavor: 'oracle'
        oracle:
          accept_oracle_download_terms: true
        oracle_rpm:
          type: 'jdk'
